version: "3.9"
services:
  postgres:
    image: postgres:13
    container_name: file_storage_postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "127.0.0.1:5432:5432"
    networks:
      - file_storage

  elastic:
    image: elasticsearch:7.14.1
    container_name: file_storage_elastic
    restart: always
    environment:
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elastic:/usr/share/elasticsearch/data
    ports:
      - "127.0.0.1:9200:9200"
    networks:
      - file_storage

  kibana:
    image: kibana:7.14.1
    container_name: file_storage_kibana
    environment:
      SERVER_NAME: kibana.local.example.com
      ELASTICSEARCH_HOSTS: '["http://elastic:9200"]'
    links:
      - elastic
    ports:
      - "127.0.0.1:5601:5601"
    networks:
      - file_storage

networks:
  file_storage:
    driver: bridge

volumes:
  postgres:
  elastic: